/* Drop Tables */

DROP TABLE BEDTIME CASCADE CONSTRAINTS;
DROP TABLE DR_OP CASCADE CONSTRAINTS;
DROP TABLE Exercise CASCADE CONSTRAINTS;
DROP TABLE MEAL CASCADE CONSTRAINTS;
DROP TABLE Daily CASCADE CONSTRAINTS;
DROP TABLE SENSORLOG CASCADE CONSTRAINTS;
DROP TABLE PATIENT CASCADE CONSTRAINTS;
DROP TABLE NURSE CASCADE CONSTRAINTS;
DROP TABLE ROOM CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE BEDTIME
(
	PT_NO number NOT NULL,
	TODAY date DEFAULT SYSDATE NOT NULL,
	TIME date,
	DELETEDATE date NOT NULL
);


CREATE TABLE DAILY
(
	PT_NO number NOT NULL UNIQUE,
	TODAY date DEFAULT SYSDATE NOT NULL,
	CLEANING date,
	WASH date,
	SHOWER date,
	REPORT varchar2(300),
	INPUTDATE date DEFAULT SYSDATE NOT NULL,
	UPDATEDATE date,
	DELETEDATE date DEFAULT SYSDATE,
	DELETEFLAG number,
	PRIMARY KEY (DAILY_PT_NO_PK, TODAY)
);


CREATE TABLE DR_OP
(
	PT_NO number NOT NULL,
	TODAY date DEFAULT SYSDATE NOT NULL,
	TEXT varchar2(300),
	DELETEFLAG number
);


CREATE TABLE Exercise
(
	PT_NO number NOT NULL,
	TODAY date DEFAULT SYSDATE NOT NULL,
	TEXT varchar2(100),
	DELETEDATE date NOT NULL
);


CREATE TABLE MEAL
(
	PT_NO number NOT NULL,
	TODAY date DEFAULT SYSDATE NOT NULL,
	BREAKFAST varchar2(150),
	LUNCH varchar2(150),
	DINNER varchar2(150),
	SNACK varchar2(50),
	DELETEFLAG number NOT NULL
);


CREATE TABLE NURSE
(
	NURSE_NO number NOT NULL UNIQUE,
	CERT_NO varchar2(20) NOT NULL UNIQUE,
	ID varchar2(13) NOT NULL UNIQUE,
	PASSWORD varchar2(15) NOT NULL,
	NAME varchar2(51) NOT NULL,
	PHONE varchar2(13) NOT NULL,
	ORIGINALPHOTO varchar2(200) NOT NULL,
	SAVEDPHOTO varchar2(200),
	INPUTDATE date DEFAULT SYSDATE NOT NULL,
	UPDATEDATE date DEFAULT SYSDATE,
	DELETEDATE date DEFAULT SYSDATE,
	DELETEFLAG number NOT NULL,
	PRIMARY KEY (NURSE_NURSE_NO_PK)
);


CREATE TABLE PATIENT
(
	PT_NO number NOT NULL,
	NURSE_NO number NOT NULL UNIQUE,
	INS_NO varchar2(20) NOT NULL UNIQUE,
	NAME varchar2(51) NOT NULL,
	BIRTHDATE varchar2(10) NOT NULL,
	DESEASE varchar2(200),
	PHONE varchar2(13),
	ADDRESS varchar2(100),
	DETAIL_ADD varchar2(50),
	ORIGINALPHOTO varchar2(200) NOT NULL,
	SAVEDPHOTO varchar2(200) NOT NULL,
	ROOM_NO varchar2(5) NOT NULL UNIQUE,
	PPT_ID varchar2(13) UNIQUE,
	PPT_PW varchar2(15),
	PPT_NAME varchar2(51),
	PPT_PHONE varchar2(13),
	PPT_ADD varchar2(100),
	PPT_DET_ADD varchar2(50),
	INPUTDATE date DEFAULT SYSDATE NOT NULL,
	UPDATEDATE date DEFAULT SYSDATE,
	DELETEDATE date DEFAULT SYSDATE,
	DELETEFLAG number NOT NULL,
	PRIMARY KEY (PT_PT_NO_PK)
);


CREATE TABLE ROOM
(
	ROOM_NO varchar2(5) NOT NULL UNIQUE,
	MAXIMUM number NOT NULL,
	PRESENT number NOT NULL,
	DELETEFLAG number NOT NULL,
	PRIMARY KEY (ROOM_ROOM_NO_PK)
);


CREATE TABLE SENSORLOG
(
	PT_NO number NOT NULL,
	TIME date NOT NULL,
	TEXT varchar2(100) NOT NULL,
	GRADE number NOT NULL
);



/* Create Foreign Keys */

ALTER TABLE BEDTIME
	ADD FOREIGN KEY (PT_NO_FK, TODAY)
	REFERENCES DAILY (DAILY_PT_NO_PK, TODAY)
;


ALTER TABLE DR_OP
	ADD FOREIGN KEY (PT_NO_FK, TODAY)
	REFERENCES DAILY (DAILY_PT_NO_PK, TODAY)
;


ALTER TABLE Exercise
	ADD FOREIGN KEY (PT_NO, TODAY)
	REFERENCES DAILY (DAILY_PT_NO_PK, TODAY)
;


ALTER TABLE MEAL
	ADD FOREIGN KEY (PT_NO_FK, TODAY)
	REFERENCES DAILY (DAILY_PT_NO_PK, TODAY)
;


ALTER TABLE PATIENT
	ADD FOREIGN KEY (NURSE_NO_FK)
	REFERENCES NURSE (NURSE_NURSE_NO_PK)
;


ALTER TABLE DAILY
	ADD FOREIGN KEY (PT_NO_FK)
	REFERENCES PATIENT (PT_PT_NO_PK)
;


ALTER TABLE SENSORLOG
	ADD FOREIGN KEY (PT_NO_FK)
	REFERENCES PATIENT (PT_PT_NO_PK)
;


ALTER TABLE PATIENT
	ADD FOREIGN KEY (ROOM_NO_FK)
	REFERENCES ROOM (ROOM_ROOM_NO_PK)
;